volumes:
  mysql-data:
  attachment-data:

services:
  nginx:
    image: nginx:latest
    container_name: nginx

    depends_on:
      tomcat:
        condition: service_started

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ../nginx/conf.d:/etc/nginx/conf.d:ro
      - /home/kohei19931226/certs:/etc/nginx/certs:ro

    networks:
      - app-network
  tomcat:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.tomcat
    container_name: my-tomcat

    volumes:
      # - ../target/app.war:/usr/local/tomcat/webapps/ROOT.war
      - ../target/app:/usr/local/tomcat/webapps/ROOT
      - attachment-data:/var/lib/nwproject/attachments

    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - app-network
    environment:
      JPDA_ADDRESS: "*:5005"
      JPDA_TRANSPORT: dt_socket
      ATTACHMENT_DIR: /var/lib/nwproject/attachments
    command: ["catalina.sh", "jpda", "run"]
    env_file:
      - ../.env
  app:
    container_name: javadev
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspaces:cached

    command: sleep infinity

    depends_on:
      db:
        condition: service_healthy

    networks:
      - app-network

    env_file:
      - ../.env

  db:
    container_name: mysqldb
    image: mysql:8.0
    restart: unless-stopped

    command:
      --default-time-zone=+09:00

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD must be set}
      MYSQL_DATABASE: ${DB_NAME:?DB_NAME must be set}
      MYSQL_USER: ${DB_USER:?DB_USER must be set}
      MYSQL_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD must be set}
      TZ: Asia/Tokyo

    ports:
      - "3307:3306"

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
       - mysql-data:/var/lib/mysql

    networks:
      - app-network

  flyway:
    image: flyway/flyway:11

    depends_on:
      db:
        condition: service_healthy

    command:
      - migrate

    volumes:
      - ./migration:/flyway/sql

    environment:
      FLYWAY_URL: jdbc:mysql://db:3306/${DB_NAME:?DB_NAME must be set}?allowPublicKeyRetrieval=true&useSSL=false
      FLYWAY_USER: ${DB_USER:?DB_USER must be set}
      FLYWAY_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD must be set}

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
