#!/bin/bash

set -e

PROJECT_DIR="$HOME/nwproject_docker"

cd "$PROJECT_DIR"

chmod +x mvnw

# target may have been generated by a Docker container (root or a different UID).
# Normalize only the Maven output directory before `clean` so the deploy user can
# safely replace the exploded WAR after a VM recreation or containerized build.
if [ -d "$PROJECT_DIR/target" ]; then
    sudo -n chown -R "$(id -u):$(id -g)" "$PROJECT_DIR/target"
    chmod -R u+rwX "$PROJECT_DIR/target"
fi

echo "========================================"
echo " Test & Build"
echo "========================================"

time ./mvnw --no-transfer-progress clean package

echo "========================================"
echo " Docker Deploy"
echo "========================================"

cd "$PROJECT_DIR/.devcontainer"

# MYSQL_ROOT_PASSWORD導入前の既存環境に限り、DB_PASSWORDを一時的に引き継ぐ。
# 認証情報のローテーション後は.envのMYSQL_ROOT_PASSWORDが使用される。
if ! grep -q '^MYSQL_ROOT_PASSWORD=' "$PROJECT_DIR/.env"; then
    MYSQL_ROOT_PASSWORD="$(sed -n 's/^DB_PASSWORD=//p' "$PROJECT_DIR/.env" | head -n 1)"
    if [ -z "$MYSQL_ROOT_PASSWORD" ]; then
        echo "MYSQL_ROOT_PASSWORD is not set and no legacy DB_PASSWORD is available." >&2
        exit 1
    fi
    export MYSQL_ROOT_PASSWORD
    echo "WARNING: MYSQL_ROOT_PASSWORD is missing; using the legacy DB password for this deployment." >&2
fi

# Always layer the AI Compose definition when the sibling AI project exists.
# Without this overlay, a deployment recreates Tomcat without AI_SERVICE_URL,
# causing AI response jobs to fail with ConnectException.
COMPOSE=(
    docker compose
    --env-file "$PROJECT_DIR/.env"
    -f "$PROJECT_DIR/.devcontainer/docker-compose.yml"
)
if [ -d "$HOME/My-AiCreate" ]; then
    COMPOSE+=(
        -f "$PROJECT_DIR/.devcontainer/docker-compose.ai.yml"
    )
fi

# DBは停止・再作成せず、必要な場合だけ起動する。
"${COMPOSE[@]}" up -d db

# 未適用のマイグレーションだけを実行する。
time "${COMPOSE[@]}" run --rm flyway

# 初回、またはTomcat用Dockerfile/server.xmlが変わった場合だけイメージをビルドする。
DEPLOY_CACHE_DIR="$HOME/.cache/nwproject-deploy"
TOMCAT_HASH_FILE="$DEPLOY_CACHE_DIR/tomcat-image.sha256"
CURRENT_TOMCAT_HASH="$(sha256sum "$PROJECT_DIR/.devcontainer/Dockerfile.tomcat" "$PROJECT_DIR/server.xml" | sha256sum | cut -d' ' -f1)"
PREVIOUS_TOMCAT_HASH="$(cat "$TOMCAT_HASH_FILE" 2>/dev/null || true)"

if [ -z "$("${COMPOSE[@]}" images -q tomcat)" ] || [ "$CURRENT_TOMCAT_HASH" != "$PREVIOUS_TOMCAT_HASH" ]; then
    time "${COMPOSE[@]}" build tomcat
    mkdir -p "$DEPLOY_CACHE_DIR"
    printf '%s' "$CURRENT_TOMCAT_HASH" > "$TOMCAT_HASH_FILE"
fi

# target/appはホストからマウントされるため、Tomcatだけ再作成すれば反映できる。
if [ -d "$HOME/My-AiCreate" ]; then
    "${COMPOSE[@]}" up -d ai-service
fi
"${COMPOSE[@]}" up -d --no-deps --force-recreate tomcat

# Nginxは起動していなければ起動し、稼働中なら再作成しない。
"${COMPOSE[@]}" up -d --no-deps nginx

echo "========================================"
echo " Health Check"
echo "========================================"

time bash "$PROJECT_DIR/scripts/healthcheck.sh"

echo "========================================"
echo " Deploy Complete"
echo "========================================"
