name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ソース取得
      - uses: actions/checkout@v4

      # Google Cloud認証(OIDC)
      - name: Authenticate
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Debug
        run: |
            echo "PROJECT=${{ secrets.GCP_PROJECT_ID }}"
            echo "SA=${{ secrets.GCP_SERVICE_ACCOUNT }}"
            echo "PROVIDER=${{ secrets.GCP_WORKLOAD_PROVIDER }}"

      # gcloudセットアップ
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # デプロイ
      - name: Deploy
        run: |
          gcloud compute ssh \
            ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }} \
            --zone=${{ secrets.GCP_ZONE }} \
            --quiet \
            --command="cd ~/nwproject_docker && chmod +x scripts/deploy.sh && ./scripts/deploy.sh"