name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main   # mainならmainに変更

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Connect Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/workspace/nwproject_docker
            git pull
            chmod +x mvnw
            ./mvnw clean install
            cd .devcontainer
            docker compose up -d --build