name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main   # mainならmainに変更

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Connect Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
          tags: tag:ci

      - name: Check Tailscale
        run: |
          tailscale status
          ping -c 3 ${{ secrets.HOST }}

      - name: Check SSH Port
        run: |
          nc -zv ${{ secrets.HOST }} 22

      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/workspace/nwproject_docker
            git pull
            chmod +x mvnw
            ./mvnw clean install
            cd .devcontainer
            docker compose up -d --build